//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtosLott.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OtosLott.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Év;Hét;Húzásdátum;5 találat (db);5 találat (Ft);4 találat (db);4 találat (Ft);3 találat (db);3 találat (Ft);2 találat (db);2 találat (Ft);Számok;;;;
        ///2023;9;2023.03.04;0;0 Ft;52;1 001 790 Ft;3663;14 840 Ft;92827;1 975 Ft;2;4;44;48;73
        ///2023;8;2023.02.25;0;0 Ft;15;3 322 140 Ft;1949;26 680 Ft;63814;2 750 Ft;2;43;72;74;82
        ///2023;7;2023.02.18;0;0 Ft;65;768 605 Ft;2923;17 835 Ft;71521;2 460 Ft;28;37;53;68;84
        ///2023;6;2023.02.11;0;0 Ft;22;2 285 905 Ft;1904;27 560 Ft;55687;3 180 Ft;10;32;40;70;82
        ///2023;5;2023.02.04;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string otoslott {
            get {
                return ResourceManager.GetString("otoslott", resourceCulture);
            }
        }
    }
}
